#!/bin/bash

usage="-- creates single-end .sam file from a single fastq file

Usage: $(basename "$0") [-h] [-a is|bwtsw] <in.fa> <ref.fa> 
where:
    -h 	show this help text
"

aligner=""
while getopts ':ha:' option; do
    case "$option" in
        h)  echo "$usage"
            exit
            ;;
	a)  aligner=$OPTARG
	    ;;
	
        ?)  printf "\nillegal option: '%s'\n" "$OPTARG" >&2
            echo "$usage" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

expected_args=2
if [ $# -lt $expected_args ]
then
    echo "$usage"
    exit 1
elif [ $# -gt 4 ]
then
    echo "$usage"
    exit 1
fi

in1="$(readlink -f "$1")"
in1name="${in1%.*}"
aln1="$in1name-aln.sai"
sam="$in1name-BWA-PAIRED.sam"

exec &> "$in1name.log"

echo "Indexing..."
/home/wflynn/tools/bwa-0.6.2/bwa index -a $aligner $i2
echo "Aligning reads..."
/home/wflynn/tools/bwa-0.6.2/bwa aln -R 100 $2 $1 > $aln1 
echo "Mapping reads..."
/home/wflynn/tools/bwa-0.6.2/bwa samse $2 $aln1 $1 > $sam
